package penggajian;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import com.mysql.jdbc.Driver;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ASUS
 */
public class gaji extends javax.swing.JInternalFrame {
    
    

    /**
     * Creates new form gaji
     */
    DefaultTableModel model;
    public gaji() {
        initComponents();
        String [] judul = {"Kd.Gaji","NIP","Kd.Jabatan","Tunj.Jabatan","Kd.Gol","GAPOK","Status",
                            "Tunj.Istri","Jml Anak","Tunj.Anak","ASKES","Lembur","UangLembur","TotalGaji"};
        model = new DefaultTableModel(judul, 0);
        tabel_gaji.setModel(model);
        tampil();
        Data();
        DataGolongan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnip = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_print = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_gaji = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtkode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cb_jabatan = new javax.swing.JComboBox();
        txttj = new javax.swing.JTextField();
        cb_golongan = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtgapok = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cb_status = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtistri = new javax.swing.JTextField();
        cb_anak = new javax.swing.JComboBox();
        txtanak = new javax.swing.JTextField();
        txtaskes = new javax.swing.JTextField();
        cb_lembur = new javax.swing.JComboBox();
        txt_lembur = new javax.swing.JTextField();
        btn_hitung = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txt_total = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();
        btn_cari = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jPanel1.setBackground(new java.awt.Color(153, 204, 0));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PENGGAJIAN KARYAWAN");

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jLabel3.setText("NIP");

        btn_simpan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penggajian/savetheapplication_guardar_2958.png"))); // NOI18N
        btn_simpan.setText("SIMPAN");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_update.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penggajian/update-cloud_icon-icons.com_54229.png"))); // NOI18N
        btn_update.setText("UPDATE");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penggajian/trash_bin_icon-icons.com_67981.png"))); // NOI18N
        btn_delete.setText("DELETE");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_clear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penggajian/clear_icon_155649 (1).png"))); // NOI18N
        btn_clear.setText("CLEAR");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_print.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penggajian/iconfinder-print-4341315_120555.png"))); // NOI18N
        btn_print.setText("PRINT");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });

        tabel_gaji.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_gaji.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_gajiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_gaji);

        jLabel10.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jLabel10.setText("KODE GOLONGAN");

        jLabel11.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jLabel11.setText("KODE JABATAN");

        jLabel12.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jLabel12.setText("KODE GAJI");

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jLabel5.setText("TUNJANGAN JABATAN");

        cb_jabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_jabatanActionPerformed(evt);
            }
        });

        cb_golongan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_golonganActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jLabel2.setText("GAJI POKOK");

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jLabel4.setText("STATUS");

        cb_status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Pilih--", "Menikah", "Belum Menikah", " " }));
        cb_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_statusActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jLabel6.setText("TUNJANGAN ISTRI");

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jLabel7.setText("JUMLAH ANAK");

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jLabel8.setText("TUNJANGAN ANAK");

        jLabel9.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jLabel9.setText("ASKES");

        jLabel13.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jLabel13.setText("LEMBUR");

        jLabel14.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jLabel14.setText("UANG LEMBUR");

        cb_anak.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Pilih--", "0", "1", "2" }));
        cb_anak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_anakActionPerformed(evt);
            }
        });

        cb_lembur.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Pilih--", "0", "1", "2", "3", "4", "5" }));
        cb_lembur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_lemburActionPerformed(evt);
            }
        });

        btn_hitung.setText("HITUNG");
        btn_hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hitungActionPerformed(evt);
            }
        });

        jLabel15.setText("TOTAL GAJI");

        txt_total.setBackground(new java.awt.Color(255, 255, 255));
        txt_total.setOpaque(true);

        btn_cari.setText("Search");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 998, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_cari))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_simpan)
                                .addGap(18, 18, 18)
                                .addComponent(btn_update)
                                .addGap(18, 18, 18)
                                .addComponent(btn_delete)
                                .addGap(18, 18, 18)
                                .addComponent(btn_clear)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_print)
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel15)
                                .addComponent(btn_hitung))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1016, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(288, 288, 288))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtgapok, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cb_golongan, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txttj, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtnip)
                                    .addComponent(txtkode)
                                    .addComponent(cb_jabatan, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cb_status, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel8))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cb_lembur, javax.swing.GroupLayout.Alignment.LEADING, 0, 161, Short.MAX_VALUE)
                                        .addComponent(txtanak, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtaskes, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(txt_lembur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtistri)
                                    .addComponent(cb_anak, 0, 161, Short.MAX_VALUE))
                                .addGap(213, 213, 213)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addGap(16, 16, 16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtkode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(cb_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtistri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(cb_anak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtanak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtaskes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel13)
                                        .addComponent(cb_golongan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10))
                                    .addComponent(cb_lembur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(txt_lembur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_hitung)
                                    .addComponent(txtgapok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(cb_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_delete)
                            .addComponent(btn_update)
                            .addComponent(btn_simpan)
                            .addComponent(btn_clear)
                            .addComponent(btn_print))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_cari)))
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/penggajian","root","");
            cn.createStatement().executeUpdate("insert into gaji values"+""
                    +"('"+txtkode.getText()+"',"
                    +"'"+txtnip.getText()+"',"
                    +"'"+cb_jabatan.getSelectedItem()+"',"
                    +"'"+txttj.getText()+"',"
                    +"'"+cb_golongan.getSelectedItem()+"',"
                    +"'"+txtgapok.getText()+"',"
                    +"'"+cb_status.getSelectedItem()+"',"
                    +"'"+txtistri.getText()+"',"
                    +"'"+cb_anak.getSelectedItem()+"',"
                    +"'"+txtanak.getText()+"',"
                    +"'"+txtaskes.getText()+"',"
                    +"'"+cb_lembur.getSelectedItem()+"',"
                    +"'"+txt_lembur.getText()+"',"
                    +"'"+txt_total.getText()+"')");
            tampil();
            clear();
            JOptionPane.showMessageDialog(null, "DATA TERSIMPAN");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void cb_anakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_anakActionPerformed
        // TODO add your handling code here:
        int pilih = cb_anak.getSelectedIndex();
        switch(pilih){
            case 0:
            case 1:
                txtanak.setText("0"); break;
            case 2:
                txtanak.setText("500000"); break;
            case 3:
                txtanak.setText("1000000");
        }
    }//GEN-LAST:event_cb_anakActionPerformed

    private void cb_lemburActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_lemburActionPerformed
        // TODO add your handling code here:
        int pilih = cb_lembur.getSelectedIndex();
        switch(pilih){
            case 0:
            case 1:
                txt_lembur.setText("0"); break; 
            case 2:
                txt_lembur.setText("50000"); break;
            case 3:
                txt_lembur.setText("100000"); break;
            case 4:
                txt_lembur.setText("150000"); break;
            case 5:
                txt_lembur.setText("200000"); break;
            case 6:
                txt_lembur.setText("250000");
        }
    }//GEN-LAST:event_cb_lemburActionPerformed

    private void cb_jabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_jabatanActionPerformed
        // TODO add your handling code here:
         try {
            Connection cn = koneksi.getConnection();
            String sql = "select * from jabatan where kode_jabatan ='" +cb_jabatan.getSelectedItem()+"'";
            Statement st = (Statement) cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()){
                txttj.setText(rs.getString("tunjangan_jabatan"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_cb_jabatanActionPerformed

    private void cb_golonganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_golonganActionPerformed
        // TODO add your handling code here:
        try {
            Connection cn = koneksi.getConnection();
            String sql = "select * from golongan where kode_golongan ='" +cb_golongan.getSelectedItem()+"'";
            Statement st = (Statement) cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()){
                txtgapok.setText(rs.getString("gapok"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_cb_golonganActionPerformed

    private void tabel_gajiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_gajiMouseClicked
        // TODO add your handling code here:
        int i = tabel_gaji.getSelectedRow();
        if(i>-1){
            txtkode.setText(model.getValueAt(i, 0).toString());
            txtnip.setText(model.getValueAt(i, 1).toString());
            cb_jabatan.setSelectedItem(model.getValueAt(i, 2).toString());
            txttj.setText(model.getValueAt(i, 3).toString());
            cb_golongan.setSelectedItem(model.getValueAt(i, 4).toString());
            txtgapok.setText(model.getValueAt(i, 5).toString());
            cb_status.setSelectedItem(model.getValueAt(i, 6).toString());
            txtistri.setText(model.getValueAt(i, 7).toString());
            cb_anak.setSelectedItem(model.getValueAt(i, 8).toString());
            txtanak.setText(model.getValueAt(i, 9).toString());
            txtaskes.setText(model.getValueAt(i, 10).toString());
            cb_lembur.setSelectedItem(model.getValueAt(i, 11).toString());
            txt_lembur.setText(model.getValueAt(i, 12).toString());
            txt_total.setText(model.getValueAt(i, 13).toString());
        }
    }//GEN-LAST:event_tabel_gajiMouseClicked

    private void btn_hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hitungActionPerformed
        // TODO add your handling code here:
        int tj = Integer.valueOf(txttj.getText());
        int gapok = Integer.valueOf(txtgapok.getText());
        int istri = Integer.valueOf(txtistri.getText());
        int anak = Integer.valueOf(txtanak.getText());
        int askes = Integer.valueOf(txtaskes.getText());
        int lembur = Integer.valueOf(txt_lembur.getText());
        int total_gaji = tj + gapok + istri + anak + askes + lembur;
        txt_total.setText(String.valueOf(total_gaji));
        
    }//GEN-LAST:event_btn_hitungActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
         try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/penggajian","root","");
            cn.createStatement().executeUpdate("update gaji set nip='"+txtnip.getText()+"',"
                    +"kode_jabatan='"+cb_jabatan.getSelectedItem()+"',"
                    +"tunjangan_jabatan='"+txttj.getText()+"',"
                    +"kode_golongan='"+cb_golongan.getSelectedItem()+"',"
                    +"gapok='"+txtgapok.getText()+"',"
                    +"status='"+cb_status.getSelectedItem()+"',"
                    +"tunjangan_istri='"+txtistri.getText()+"',"
                    +"jumlah_anak='"+cb_anak.getSelectedItem()+"',"
                    +"tunjangan_anak='"+txtanak.getText()+"',"
                    +"askes='"+txtaskes.getText()+"',"
                    +"lembur='"+cb_lembur.getSelectedItem()+"',"
                    +"uang_lembur='"+txt_lembur.getText()+"',"
                    +"total_gaji='"+txt_total.getText()+"'"
                    +"where kode_gaji='"+txtkode.getText()+"'");
            tampil();
            clear();
            JOptionPane.showMessageDialog(null, "DATA TERUPDATE");
        } catch (SQLException ex) {
            Logger.getLogger(jabatan.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "DATA GAGAL DIUPDATE");
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/penggajian","root","");
            cn.createStatement().executeUpdate("delete from gaji where kode_gaji='"+txtkode.getText()+"'");
            JOptionPane.showMessageDialog(null, "DATA TERHAPUS");
            tampil();
            clear();
        } catch (SQLException ex) {
            Logger.getLogger(jabatan.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "DATA GAGAL DIHAPUS");
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void cb_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_statusActionPerformed
        // TODO add your handling code here:
        int pilih = cb_status.getSelectedIndex();
        switch(pilih){
            case 0:
            case 1:
                break;
            case 2:
                txtistri.setText("0");
                cb_anak.setSelectedItem("0");
        }
    }//GEN-LAST:event_cb_statusActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:
        String key = txtcari.getText();
        System.out.println(key);
        if(!"".equals(key)){
            cari(key);
        }else{
            tampil();
        }
    }//GEN-LAST:event_btn_cariActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        // TODO add your handling code here:
        cetak_penggajian a = new cetak_penggajian();
        a.setVisible(true);
    }//GEN-LAST:event_btn_printActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_hitung;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox cb_anak;
    private javax.swing.JComboBox cb_golongan;
    private javax.swing.JComboBox cb_jabatan;
    private javax.swing.JComboBox cb_lembur;
    private javax.swing.JComboBox cb_status;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_gaji;
    private javax.swing.JTextField txt_lembur;
    private javax.swing.JLabel txt_total;
    private javax.swing.JTextField txtanak;
    private javax.swing.JTextField txtaskes;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtgapok;
    private javax.swing.JTextField txtistri;
    private javax.swing.JTextField txtkode;
    private javax.swing.JTextField txtnip;
    private javax.swing.JTextField txttj;
    // End of variables declaration//GEN-END:variables

    private void clear(){
        txtkode.setText("");
        txtnip.setText("");
        cb_jabatan.setSelectedItem("--Pilih--");
        txttj.setText("");
        cb_golongan.setSelectedItem("--Pilih--");
        txtgapok.setText("");
        cb_status.setSelectedItem("--Pilih--");
        txtistri.setText("");
        cb_anak.setSelectedItem("--Pilih--");
        txtanak.setText("");
        txtaskes.setText("");
        cb_lembur.setSelectedItem("--Pilih--");
        txt_lembur.setText("");
        txt_total.setText("");
    }
    
    private void tampil(){
        int row = tabel_gaji.getRowCount();
        for(int a=0; a<row; a++){
            model.removeRow(0);
        }
        try {
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/penggajian","root","");
                ResultSet rs = cn.createStatement().executeQuery("select * from gaji");
                while(rs.next()){
                    String data[] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)
                    ,rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10),
                    rs.getString(11),rs.getString(12),rs.getString(13),rs.getString(14)};
                    model.addRow(data);
                }
        } catch (SQLException ex) {
            Logger.getLogger(gaji.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void Data(){
      try {
            cb_jabatan.removeAllItems();
            cb_jabatan.addItem("Pilih");
            String sql = "select * from jabatan order by kode_jabatan asc";
            Statement st = (Statement) koneksi.getConnection().createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                        cb_jabatan.addItem(rs.getString("kode_jabatan"));
               }
            rs.close();
        } catch (SQLException e) {
            
        }
        }
        
      private void DataGolongan(){
      try {
            cb_golongan.removeAllItems();
            cb_golongan.addItem("Pilih");
            String sql = "select * from golongan order by kode_golongan";
            Statement st = (Statement) koneksi.getConnection().createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                        cb_golongan.addItem(rs.getString("kode_golongan"));
               }
            rs.close();;
        } catch (SQLException e) {
            
        }
        }
      
      private void cari(String key){
          try {
              Object[] judul_kolom = {"Kd.Gaji","NIP","Kd.Jabatan","Tunj.Jabatan","Kd.Gol","GAPOK","Status",
                            "Tunj.Istri","Jml Anak","Tunj.Anak","ASKES","Lembur","UangLembur","TotalGaji"};
              model = new DefaultTableModel(null,judul_kolom);
              tabel_gaji.setModel(model);
              
              Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/penggajian","root","");
              Statement stt = cn.createStatement();
              model.getDataVector().removeAllElements();
              ResultSet rs = stt.executeQuery("Select * from gaji where kode_gaji LIKE '%"+key+"%'");
              while(rs.next()){
                  Object[] data={
                      rs.getString(1),
                      rs.getString(2),
                      rs.getString(3),
                      rs.getString(4),
                      rs.getString(5),
                      rs.getString(6),
                      rs.getString(7),
                      rs.getString(8),
                      rs.getString(9),
                      rs.getString(10),
                      rs.getString(11),
                      rs.getString(12),
                      rs.getString(13),
                      rs.getString(14)
                  };
                  model.addRow(data);
              }
          } catch (Exception ex) {
              System.err.println(ex.getMessage());
          }
      }
    }